# Generated by Django 5.1.1 on 2024-12-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testiomonials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
