# Generated by Django 5.1.1 on 2024-12-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testiomonials', '0002_testimonial_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='class_name',
            field=models.CharField(choices=[('TOEFL Preparation', 'TOEFL Preparation'), ('Class Grammar', 'Class Grammar'), ('Class Reading', 'Class Reading'), ('Class Listening', 'Class Listening'), ('IELTS Preparation', 'IELTS Preparation'), ('Class Writing', 'Class Writing'), ('Class Speaking', 'Class Speaking'), ('Business English', 'Business English')], default='TOEFL Preparation', max_length=100),
        ),
    ]
