# Generated by Django 5.1.3 on 2024-12-14 16:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(choices=[('Kelas Grammar', 'Kelas Grammar'), ('Kelas Listening', 'Kelas Listening'), ('Kelas Reading', 'Kelas Reading'), ('Kelas Writing', 'Kelas Writing'), ('Kelas Speaking', 'Kelas Speaking'), ('Toefl Preparation', 'Toefl Preparation'), ('Ielts Preparation', 'Ielts Preparation'), ('Business English', 'Business English')], default='Kelas Grammar', max_length=255)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=255)),
                ('harga', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('nama', models.CharField(max_length=255)),
                ('no_telpon', models.CharField(default='0000000000', max_length=15)),
                ('email', models.EmailField(default='default@example.com', max_length=225)),
                ('tanggal_pembayaran', models.DateField(auto_now_add=True)),
                ('metode_pembayaran', models.CharField(choices=[('transfer', 'Transfer'), ('BCA', 'BCA'), ('BRI', 'BRI'), ('DANA', 'DANA'), ('SHOPEEPAY', 'SHOPEEPAY')], max_length=255)),
                ('bukti_pembayaran', models.ImageField(upload_to='bukti_pembayaran/')),
                ('status_pembayaran', models.CharField(choices=[('pending', 'Pending'), ('lunas', 'Lunas'), ('ditolak', 'Ditolak')], default='pending', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
