# Generated by Django 5.1.3 on 2024-12-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaran',
            name='status_pembayaran',
            field=models.CharField(choices=[('pending', 'Pending'), ('Lunas', 'Lunas'), ('ditolak', 'Ditolak')], default='pending', max_length=20),
        ),
    ]
