# Generated by Django 5.1.1 on 2024-11-12 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField(max_length=200)),
                ('mentor_count', models.IntegerField(max_length=100)),
                ('class_count', models.IntegerField(max_length=20)),
            ],
        ),
    ]
