# Generated by Django 5.1.1 on 2024-11-12 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='count',
            name='class_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='count',
            name='mentor_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='count',
            name='student_count',
            field=models.IntegerField(),
        ),
    ]
