# Generated by Django 5.1.1 on 2024-12-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
