# Generated by Django 5.1.1 on 2024-12-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_comment_user_comment_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
