# Generated by Django 5.1.1 on 2024-11-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(max_length=150)),
                ('linkYt', models.URLField(blank=True)),
                ('linkIg', models.URLField()),
                ('linkFb', models.URLField()),
                ('image_mentor', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='class',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
