# Generated by Django 5.1.1 on 2024-12-12 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_discuss', '0002_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='topic',
        ),
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum_discuss.post'),
        ),
    ]
