# Generated by Django 5.1.1 on 2024-12-12 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum_discuss', '0003_remove_notification_topic_post_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
