# Generated by Django 5.1.1 on 2024-12-13 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_discuss', '0005_alter_post_options_alter_topic_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum_discuss.post', verbose_name='Balasan dari'),
        ),
    ]
