# Generated by Django 5.1.1 on 2024-12-13 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum_discuss', '0007_topic_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='unlikes',
            field=models.ManyToManyField(blank=True, related_name='unliked_topics', to=settings.AUTH_USER_MODEL),
        ),
    ]
