# Generated by Django 5.1.1 on 2024-11-13 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='Classpages',
        ),
    ]
