# Generated by Django 5.1.1 on 2024-11-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0002_rename_class_classpages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpages',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
