# Generated by Django 5.1.3 on 2024-11-17 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0004_alter_classpages_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='classpages',
            name='link_page',
            field=models.URLField(null=True),
        ),
    ]
