# Generated by Django 5.1.3 on 2024-11-17 15:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0005_classpages_link_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpages',
            name='link_page',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
