# Generated by Django 5.1.3 on 2024-11-20 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0007_remove_classpages_link_page_classpages_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpages',
            name='url_slug',
            field=models.CharField(max_length=50),
        ),
    ]
