# Generated by Django 5.1.3 on 2024-12-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0008_alter_classpages_url_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpages',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
    ]
