# Generated by Django 5.1.1 on 2024-12-14 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0009_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
