# Generated by Django 5.1.3 on 2024-12-15 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0009_alter_classpages_level'),
        ('classPage', '0010_delete_feedback'),
    ]

    operations = [
    ]
