# Generated by Django 5.1.3 on 2024-12-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classPage', '0011_merge_20241215_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classpages',
            name='level',
            field=models.CharField(max_length=50),
        ),
    ]
